// SPDX-FileCopyrightText: 2026 Chimera-NAS Project Contributors
//
// SPDX-License-Identifier: LGPL-2.1-only

/*
 * ndrzcc: compile an MS-IDL subset into DCE/RPC NDR marshalling C code.
 *
 * Pipeline mirrors xdrzcc: Flex/Bison build the AST (ndr.h), then this driver
 * resolves types and emits a .h (C structs + per-op in/out structs + dispatch
 * table declarations) and a .c (per-type/per-op push/pull functions + the
 * dispatch table + interface descriptor).  The runtime (ndr_builtin.h/.c) is
 * embedded into the generated files so they are self-contained.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

#include "ndr.h"

extern int yyparse(
    void);
extern FILE                 *yyin;

extern struct ndr_interface *g_iface;
extern struct ndr_struct    *g_structs;
extern struct ndr_union     *g_unions;
extern struct ndr_enum      *g_enums;
extern struct ndr_typedef   *g_typedefs;
extern struct ndr_const     *g_consts;

/* Embedded runtime (generated by generate_embedded.sh). */
extern const char           *embedded_builtin_h;
extern const char           *embedded_builtin_c;

static FILE                 *out_c;
static FILE                 *out_h;

/*
 * ndrzcc is a short-lived build-time tool that deliberately arena-leaks its AST
 * rather than walking it to free.  Disable LeakSanitizer so Debug (ASan) builds
 * don't fail the generation custom-command on exit.
 *
 * The runtime resolves __asan_default_options through libasan.so against the
 * executable's *dynamic* symbol table; the tree builds -fvisibility=hidden, so
 * the symbol must be forced to default visibility or it is invisible to the
 * sanitizer and the override is silently ignored.
 */
__attribute__((visibility("default")))
const char *
__asan_default_options(void)
{
    return "detect_leaks=0";
} /* __asan_default_options */

static void
fail(const char *msg)
{
    fprintf(stderr, "ndrzcc: %s\n", msg);
    exit(1);
} /* fail */

/* ------------------------------------------------------------------ *
* Type classification
* ------------------------------------------------------------------ */

static int
classify_builtin(const char *name)
{
    if (!strcmp(name, "uint8") || !strcmp(name, "uint8_t") ||
        !strcmp(name, "boolean") || !strcmp(name, "char") ||
        !strcmp(name, "BYTE")) {
        return NDR_BUILTIN_UINT8;
    }
    if (!strcmp(name, "uint16") || !strcmp(name, "uint16_t") ||
        !strcmp(name, "wchar_t") || !strcmp(name, "WORD")) {
        return NDR_BUILTIN_UINT16;
    }
    if (!strcmp(name, "uint32") || !strcmp(name, "uint32_t") ||
        !strcmp(name, "DWORD") || !strcmp(name, "ULONG") ||
        !strcmp(name, "NTSTATUS")) {
        return NDR_BUILTIN_UINT32;
    }
    if (!strcmp(name, "uint64") || !strcmp(name, "uint64_t") ||
        !strcmp(name, "hyper")) {
        return NDR_BUILTIN_UINT64;
    }
    if (!strcmp(name, "int8") || !strcmp(name, "int8_t")) {
        return NDR_BUILTIN_INT8;
    }
    if (!strcmp(name, "int16") || !strcmp(name, "int16_t")) {
        return NDR_BUILTIN_INT16;
    }
    if (!strcmp(name, "int32") || !strcmp(name, "int32_t") || !strcmp(name, "int")) {
        return NDR_BUILTIN_INT32;
    }
    if (!strcmp(name, "int64") || !strcmp(name, "int64_t")) {
        return NDR_BUILTIN_INT64;
    }
    if (!strcmp(name, "void")) {
        return NDR_BUILTIN_VOID;
    }
    return NDR_BUILTIN_NONE;
} /* classify_builtin */

static struct ndr_enum *
find_enum(const char *name)
{
    struct ndr_enum *e;

    NDR_FOREACH(e, g_enums)
    {
        if (!strcmp(e->name, name)) {
            return e;
        }
    }
    return NULL;
} /* find_enum */

/* Width (in bytes) and stdint C name for a builtin scalar. */
static const char *
builtin_ctype(int b)
{
    switch (b) {
        case NDR_BUILTIN_UINT8:  return "uint8_t";
        case NDR_BUILTIN_UINT16: return "uint16_t";
        case NDR_BUILTIN_UINT32: return "uint32_t";
        case NDR_BUILTIN_UINT64: return "uint64_t";
        case NDR_BUILTIN_INT8:   return "int8_t";
        case NDR_BUILTIN_INT16:  return "int16_t";
        case NDR_BUILTIN_INT32:  return "int32_t";
        case NDR_BUILTIN_INT64:  return "int64_t";
        default:                 return NULL;
    } /* switch */
} /* builtin_ctype */

static int
builtin_width(int b)
{
    switch (b) {
        case NDR_BUILTIN_UINT8:
        case NDR_BUILTIN_INT8:  return 1;
        case NDR_BUILTIN_UINT16:
        case NDR_BUILTIN_INT16: return 2;
        case NDR_BUILTIN_UINT32:
        case NDR_BUILTIN_INT32: return 4;
        case NDR_BUILTIN_UINT64:
        case NDR_BUILTIN_INT64: return 8;
        default:                return 0;
    } /* switch */
} /* builtin_width */

/*
 * The C base type (no pointer/array decoration) for a type reference.
 * Writes into buf.
 */
static const char *
c_base_type(
    struct ndr_type *t,
    char            *buf,
    size_t           buflen)
{
    int b = classify_builtin(t->name);

    if (t->is_string) {
        snprintf(buf, buflen, "char");
    } else if (t->is_sid) {
        snprintf(buf, buflen, "struct ndr_sid");
    } else if (b != NDR_BUILTIN_NONE && b != NDR_BUILTIN_VOID) {
        snprintf(buf, buflen, "%s", builtin_ctype(b));
    } else if (find_enum(t->name)) {
        snprintf(buf, buflen, "uint32_t");   /* enums stored as 32-bit */
    } else {
        snprintf(buf, buflen, "struct %s", t->name);
    }
    return buf;
} /* c_base_type */

/* ------------------------------------------------------------------ *
* Sibling-expression substitution for size_is/length_is/switch_is.
* "count"   -> "<root>->count"
* "size/2"  -> "<root>->size/2"
* ------------------------------------------------------------------ */
static void
subst_sibling(
    const char *root,
    const char *expr,
    char       *buf,
    size_t      buflen)
{
    size_t i = 0;

    while (expr[i] && (expr[i] == '_' ||
                       (expr[i] >= 'a' && expr[i] <= 'z') ||
                       (expr[i] >= 'A' && expr[i] <= 'Z') ||
                       (expr[i] >= '0' && expr[i] <= '9'))) {
        i++;
    }
    snprintf(buf, buflen, "%s->%.*s%s", root, (int) i, expr, expr + i);
} /* subst_sibling */

/* ------------------------------------------------------------------ *
* Header emission
* ------------------------------------------------------------------ */

static void
emit_field_decl(
    FILE            *f,
    struct ndr_type *t,
    const char      *name,
    int              reduce_ptr)
{
    char base[128];
    int  stars;

    c_base_type(t, base, sizeof(base));

    if (t->is_string) {
        fprintf(f, "    %s *%s;\n", base, name);
        return;
    }

    stars = t->nptr;
    if (reduce_ptr && stars > 0) {
        stars--;   /* top-level params are inherently by-reference */
    }
    /* A conformant array keeps a pointer to its elements. */
    if (t->conformant && stars == 0) {
        stars = 1;
    }

    fprintf(f, "    %s ", base);
    for (int i = 0; i < stars; i++) {
        fputc('*', f);
    }
    fprintf(f, "%s", name);
    if (t->fixed && t->fixed_size) {
        fprintf(f, "[%s]", t->fixed_size);
    }
    fprintf(f, ";\n");
} /* emit_field_decl */

static void
emit_struct_decls(void)
{
    struct ndr_enum   *e;
    struct ndr_struct *s;
    struct ndr_union  *u;

    /* enums as #defines */
    NDR_FOREACH(e, g_enums)
    {
        struct ndr_enum_entry *ent;

        fprintf(out_h, "/* enum %s */\n", e->name);
        NDR_FOREACH(ent, e->entries)
        {
            if (ent->value) {
                fprintf(out_h, "#define %s %s\n", ent->name, ent->value);
            }
        }
        fprintf(out_h, "\n");
    }

    NDR_FOREACH(u, g_unions)
    {
        struct ndr_union_case *uc;

        fprintf(out_h, "struct %s {\n", u->name);
        fprintf(out_h, "    uint32_t switch_value;\n");
        fprintf(out_h, "    union {\n");
        NDR_FOREACH(uc, u->cases)
        {
            if (uc->voided || !uc->type) {
                continue;
            }
            fprintf(out_h, "    ");
            emit_field_decl(out_h, uc->type, uc->name, 0);
        }
        fprintf(out_h, "    } u;\n");
        fprintf(out_h, "};\n\n");
    }

    NDR_FOREACH(s, g_structs)
    {
        struct ndr_member *m;

        fprintf(out_h, "struct %s {\n", s->name);
        NDR_FOREACH(m, s->members)
        {
            emit_field_decl(out_h, m->type, m->name, 0);
        }
        fprintf(out_h, "};\n\n");
    }
} /* emit_struct_decls */

static void
emit_op_io_structs(void)
{
    struct ndr_op *op;

    if (!g_iface) {
        return;
    }

    NDR_FOREACH(op, g_iface->ops)
    {
        struct ndr_param *p;

        fprintf(out_h, "struct %s_in {\n", op->name);
        NDR_FOREACH(p, op->params)
        {
            if (p->in) {
                emit_field_decl(out_h, p->type, p->name, 1);
            }
        }
        fprintf(out_h, "};\n\n");

        fprintf(out_h, "struct %s_out {\n", op->name);
        NDR_FOREACH(p, op->params)
        {
            if (p->out) {
                emit_field_decl(out_h, p->type, p->name, 1);
            }
        }
        if (op->return_type &&
            classify_builtin(op->return_type->name) != NDR_BUILTIN_VOID) {
            fprintf(out_h, "    uint32_t status;\n");
        }
        fprintf(out_h, "};\n\n");
    }
} /* emit_op_io_structs */

/* ------------------------------------------------------------------ *
* Marshalling: embedded struct members (two-pass)
* ------------------------------------------------------------------ */

static void
emit_scalar_put(
    FILE       *f,
    int         b,
    const char *acc)
{
    int w = builtin_width(b);

    fprintf(f, "    ndr_put_u%d(w, (uint%d_t) %s);\n",
            w * 8, w * 8, acc);
} /* emit_scalar_put */

static void
emit_scalar_get(
    FILE       *f,
    int         b,
    const char *acc)
{
    int w = builtin_width(b);

    fprintf(f, "    %s = ndr_get_u%d(c);\n", acc, w * 8);
} /* emit_scalar_get */

/* push of an embedded member (called once per pass) */
static void
emit_member_push(
    FILE              *f,
    struct ndr_struct *s,
    struct ndr_member *m,
    const char        *pass)
{
    struct ndr_type *t = m->type;
    char             acc[160];
    int              b = classify_builtin(t->name);

    snprintf(acc, sizeof(acc), "v->%s", m->name);

    /* ---- pointer to a conformant array of N elements ---- */
    if (t->conformant) {
        char cnt[160];
        subst_sibling("v", t->size_is, cnt, sizeof(cnt));
        if (!strcmp(pass, "NDR_SCALARS")) {
            /* the array pointer's referent id sits inline in the scalars pass;
             * the array body (max_count + elements) is deferred to buffers */
            fprintf(f, "    ndr_put_ref(w, %s);\n", acc);
        } else {
            fprintf(f, "    if (%s) {\n", acc);
            fprintf(f, "        uint32_t _n = (uint32_t)(%s);\n", cnt);
            fprintf(f, "        ndr_put_u32(w, _n);\n");   /* max_count */
            if (b != NDR_BUILTIN_NONE) {
                fprintf(f, "        for (uint32_t _i = 0; _i < _n; _i++)\n");
                fprintf(f, "            ndr_put_u%d(w, %s[_i]);\n",
                        builtin_width(b) * 8, acc);
            } else {
                fprintf(f, "        for (uint32_t _i = 0; _i < _n; _i++)\n");
                fprintf(f, "            ndr_push_%s(w, NDR_SCALARS, &%s[_i]);\n",
                        t->name, acc);
                fprintf(f, "        for (uint32_t _i = 0; _i < _n; _i++)\n");
                fprintf(f, "            ndr_push_%s(w, NDR_BUFFERS, &%s[_i]);\n",
                        t->name, acc);
            }
            fprintf(f, "    }\n");
        }
        return;
    }

    /* ---- [string] pointer ---- */
    if (t->is_string) {
        const char *pushfn = t->string_nonul ? "ndr_push_wstring_nonul" : "ndr_push_wstring";
        if (!strcmp(pass, "NDR_SCALARS")) {
            fprintf(f, "    ndr_put_ref(w, %s);\n", acc);
        } else {
            fprintf(f, "    if (%s) %s(w, %s);\n", acc, pushfn, acc);
        }
        return;
    }

    /* ---- fixed array of scalars ---- */
    if (t->fixed) {
        if (!strcmp(pass, "NDR_SCALARS") && b != NDR_BUILTIN_NONE) {
            fprintf(f, "    for (int _i = 0; _i < %s; _i++)\n", t->fixed_size);
            fprintf(f, "        ndr_put_u%d(w, %s[_i]);\n", builtin_width(b) * 8, acc);
        }
        return;
    }

    /* ---- SID ---- */
    if (t->is_sid) {
        if (t->nptr > 0) {
            if (!strcmp(pass, "NDR_SCALARS")) {
                fprintf(f, "    ndr_put_ref(w, %s);\n", acc);
            } else {
                fprintf(f, "    if (%s) ndr_push_sid(w, NDR_SCALARS, %s);\n", acc, acc);
            }
        } else if (!strcmp(pass, "NDR_SCALARS")) {
            fprintf(f, "    ndr_push_sid(w, NDR_SCALARS, &%s);\n", acc);
        }
        return;
    }

    /* ---- scalar / enum ---- */
    if (b != NDR_BUILTIN_NONE || find_enum(t->name)) {
        int bb = (b != NDR_BUILTIN_NONE) ? b : NDR_BUILTIN_UINT32;
        if (!strcmp(pass, "NDR_SCALARS")) {
            emit_scalar_put(f, bb, acc);
        }
        return;
    }

    /* ---- nested named struct ---- */
    if (t->nptr > 0) {
        if (!strcmp(pass, "NDR_SCALARS")) {
            fprintf(f, "    ndr_put_ref(w, %s);\n", acc);
        } else {
            fprintf(f, "    if (%s) {\n", acc);
            fprintf(f, "        ndr_push_%s(w, NDR_SCALARS, %s);\n", t->name, acc);
            fprintf(f, "        ndr_push_%s(w, NDR_BUFFERS, %s);\n", t->name, acc);
            fprintf(f, "    }\n");
        }
    } else {
        fprintf(f, "    ndr_push_%s(w, %s, &%s);\n", t->name, pass, acc);
    }
} /* emit_member_push */

static void
emit_member_pull(
    FILE              *f,
    struct ndr_struct *s,
    struct ndr_member *m,
    const char        *pass)
{
    struct ndr_type *t = m->type;
    char             acc[160];
    int              b = classify_builtin(t->name);

    snprintf(acc, sizeof(acc), "v->%s", m->name);

    if (t->conformant) {
        if (!strcmp(pass, "NDR_SCALARS")) {
            /* array pointer referent id */
            fprintf(f, "    %s = (void *) (uintptr_t) ndr_get_u32(c);\n", acc);
        } else {
            fprintf(f, "    if (%s) {\n", acc);
            fprintf(f, "        uint32_t _n = ndr_get_u32(c);\n");
            fprintf(f, "        %s = ndr_dbuf_alloc(d, _n * sizeof(*%s));\n", acc, acc);
            if (b != NDR_BUILTIN_NONE) {
                fprintf(f, "        for (uint32_t _i = 0; _i < _n; _i++)\n");
                fprintf(f, "            %s[_i] = ndr_get_u%d(c);\n", acc, builtin_width(b) * 8);
            } else {
                fprintf(f, "        for (uint32_t _i = 0; _i < _n; _i++)\n");
                fprintf(f, "            ndr_pull_%s(c, NDR_SCALARS, &%s[_i], d);\n", t->name, acc);
                fprintf(f, "        for (uint32_t _i = 0; _i < _n; _i++)\n");
                fprintf(f, "            ndr_pull_%s(c, NDR_BUFFERS, &%s[_i], d);\n", t->name, acc);
            }
            fprintf(f, "    }\n");
        }
        return;
    }

    if (t->is_string) {
        if (!strcmp(pass, "NDR_SCALARS")) {
            fprintf(f, "    %s = (char *)(uintptr_t) ndr_get_u32(c);\n", acc);   /* referent */
        } else {
            fprintf(f, "    if (%s) %s = ndr_pull_wstring(c, d);\n", acc, acc);
        }
        return;
    }

    if (t->fixed) {
        if (!strcmp(pass, "NDR_SCALARS") && b != NDR_BUILTIN_NONE) {
            fprintf(f, "    for (int _i = 0; _i < %s; _i++)\n", t->fixed_size);
            fprintf(f, "        %s[_i] = ndr_get_u%d(c);\n", acc, builtin_width(b) * 8);
        }
        return;
    }

    if (t->is_sid) {
        if (t->nptr > 0) {
            /* pointer to SID: referent id in scalars, deferred body in buffers */
            if (!strcmp(pass, "NDR_SCALARS")) {
                fprintf(f, "    %s = (struct ndr_sid *) (uintptr_t) ndr_get_u32(c);\n", acc);
            } else {
                fprintf(f, "    if (%s) {\n", acc);
                fprintf(f, "        %s = ndr_dbuf_alloc(d, sizeof(struct ndr_sid));\n", acc);
                fprintf(f, "        ndr_pull_sid(c, NDR_SCALARS, %s);\n", acc);
                fprintf(f, "    }\n");
            }
        } else if (!strcmp(pass, "NDR_SCALARS")) {
            fprintf(f, "    ndr_pull_sid(c, NDR_SCALARS, &%s);\n", acc);
        }
        return;
    }

    if (b != NDR_BUILTIN_NONE || find_enum(t->name)) {
        int bb = (b != NDR_BUILTIN_NONE) ? b : NDR_BUILTIN_UINT32;
        if (!strcmp(pass, "NDR_SCALARS")) {
            emit_scalar_get(f, bb, acc);
        }
        return;
    }

    /* nested named struct */
    if (t->nptr > 0) {
        /* pointer to struct: referent id in scalars, deferred pointee in buffers
         * (symmetric to emit_member_push) */
        if (!strcmp(pass, "NDR_SCALARS")) {
            fprintf(f, "    %s = (struct %s *) (uintptr_t) ndr_get_u32(c);\n", acc, t->name);
        } else {
            fprintf(f, "    if (%s) {\n", acc);
            fprintf(f, "        %s = ndr_dbuf_alloc(d, sizeof(struct %s));\n", acc, t->name);
            fprintf(f, "        ndr_pull_%s(c, NDR_SCALARS, %s, d);\n", t->name, acc);
            fprintf(f, "        ndr_pull_%s(c, NDR_BUFFERS, %s, d);\n", t->name, acc);
            fprintf(f, "    }\n");
        }
    } else {
        fprintf(f, "    ndr_pull_%s(c, %s, &%s, d);\n", t->name, pass, acc);
    }
} /* emit_member_pull */

static void
emit_type_funcs(void)
{
    struct ndr_struct *s;
    struct ndr_union  *u;

    NDR_FOREACH(u, g_unions)
    {
        struct ndr_union_case *uc;

        /* push */
        fprintf(out_c, "void\nndr_push_%s(struct ndr_writer *w, int flags, const struct %s *v)\n{\n",
                u->name, u->name);
        if (u->encapsulated) {
            fprintf(out_c, "    if (flags & NDR_SCALARS) ndr_put_u32(w, v->switch_value);\n");
        }
        fprintf(out_c, "    switch (v->switch_value) {\n");
        NDR_FOREACH(uc, u->cases)
        {
            if (uc->is_default) {
                fprintf(out_c, "    default:\n");
            } else {
                fprintf(out_c, "    case %s:\n", uc->label);
            }
            if (!uc->voided && uc->type) {
                /* treat the arm like a one-off member */
                struct ndr_member tmp = { .type = uc->type, .name = NULL };
                char              arm[160];
                snprintf(arm, sizeof(arm), "u.%s", uc->name);
                tmp.name = arm;
                fprintf(out_c, "        if (flags & NDR_SCALARS) {\n");
                emit_member_push(out_c, NULL, &tmp, "NDR_SCALARS");
                fprintf(out_c, "        }\n        if (flags & NDR_BUFFERS) {\n");
                emit_member_push(out_c, NULL, &tmp, "NDR_BUFFERS");
                fprintf(out_c, "        }\n");
            }
            fprintf(out_c, "        break;\n");
        }
        fprintf(out_c, "    }\n}\n\n");

        /* pull (scalars discriminant only; arms minimal) */
        fprintf(out_c, "void\nndr_pull_%s(struct ndr_cursor *c, int flags, struct %s *v, struct ndr_dbuf *d)\n{\n",
                u->name, u->name);
        if (u->encapsulated) {
            fprintf(out_c, "    if (flags & NDR_SCALARS) v->switch_value = ndr_get_u32(c);\n");
        }
        fprintf(out_c, "    (void) c; (void) d;\n");
        fprintf(out_c, "}\n\n");
    }

    NDR_FOREACH(s, g_structs)
    {
        struct ndr_member *m;

        /* push */
        fprintf(out_c, "void\nndr_push_%s(struct ndr_writer *w, int flags, const struct %s *v)\n{\n",
                s->name, s->name);
        fprintf(out_c, "    if (flags & NDR_SCALARS) {\n");
        NDR_FOREACH(m, s->members)
        {
            emit_member_push(out_c, s, m, "NDR_SCALARS");
        }
        fprintf(out_c, "    }\n    if (flags & NDR_BUFFERS) {\n");
        NDR_FOREACH(m, s->members)
        {
            emit_member_push(out_c, s, m, "NDR_BUFFERS");
        }
        fprintf(out_c, "    }\n}\n\n");

        /* pull */
        fprintf(out_c, "void\nndr_pull_%s(struct ndr_cursor *c, int flags, struct %s *v, struct ndr_dbuf *d)\n{\n",
                s->name, s->name);
        fprintf(out_c, "    if (flags & NDR_SCALARS) {\n");
        NDR_FOREACH(m, s->members)
        {
            emit_member_pull(out_c, s, m, "NDR_SCALARS");
        }
        fprintf(out_c, "    }\n    if (flags & NDR_BUFFERS) {\n");
        NDR_FOREACH(m, s->members)
        {
            emit_member_pull(out_c, s, m, "NDR_BUFFERS");
        }
        fprintf(out_c, "    }\n    (void) d;\n}\n\n");
    }

    /* forward declarations in the header */
    NDR_FOREACH(u, g_unions)
    {
        fprintf(out_h, "void ndr_push_%s(struct ndr_writer *w, int flags, const struct %s *v);\n", u->name, u->name);
        fprintf(out_h, "void ndr_pull_%s(struct ndr_cursor *c, int flags, struct %s *v, struct ndr_dbuf *d);\n", u->name
                , u->name);
    }
    NDR_FOREACH(s, g_structs)
    {
        fprintf(out_h, "void ndr_push_%s(struct ndr_writer *w, int flags, const struct %s *v);\n", s->name, s->name);
        fprintf(out_h, "void ndr_pull_%s(struct ndr_cursor *c, int flags, struct %s *v, struct ndr_dbuf *d);\n", s->name
                , s->name);
    }
    fprintf(out_h, "\n");
} /* emit_type_funcs */

/* ------------------------------------------------------------------ *
* Top-level operation params
* ------------------------------------------------------------------ */

/* whether a top-level pointer param carries a referent id (unique/full do) */
static int
param_has_referent(struct ndr_param *p)
{
    return p->type->nptr > 0 &&
           (p->type->ptr == NDR_PTR_UNIQUE || p->type->ptr == NDR_PTR_FULL);
} /* param_has_referent */

static void
emit_op_funcs(void)
{
    struct ndr_op *op;

    if (!g_iface) {
        return;
    }

    NDR_FOREACH(op, g_iface->ops)
    {
        struct ndr_param *p;

        /* ---- pull_in ---- */
        fprintf(out_c, "static int\nndr_pull_%s_in(struct ndr_cursor *c, void *vp, struct ndr_dbuf *d)\n{\n",
                op->name);
        fprintf(out_c, "    struct %s_in *in = vp;\n", op->name);
        fprintf(out_c, "    (void) in; (void) d;\n");
        NDR_FOREACH(p, op->params)
        {
            struct ndr_type *t = p->type;
            char             acc[160];
            int              b = classify_builtin(t->name);

            if (!p->in) {
                continue;
            }
            snprintf(acc, sizeof(acc), "in->%s", p->name);

            if (t->conformant) {
                /* [in, size_is(...)] T *arr : a top-level (ref) conformant
                 * array -- no referent id, just the hoisted max_count then the
                 * elements.  The element count is also carried by the sibling
                 * size_is parameter, which the handler reads directly. */
                fprintf(out_c, "    {\n");
                fprintf(out_c, "        uint32_t _n = ndr_get_u32(c);\n");
                fprintf(out_c, "        %s = ndr_dbuf_alloc(d, _n * sizeof(*%s));\n", acc, acc);
                if (b != NDR_BUILTIN_NONE) {
                    fprintf(out_c, "        for (uint32_t _i = 0; _i < _n; _i++)\n");
                    fprintf(out_c, "            %s[_i] = ndr_get_u%d(c);\n", acc, builtin_width(b) * 8);
                } else {
                    fprintf(out_c, "        for (uint32_t _i = 0; _i < _n; _i++)\n");
                    fprintf(out_c, "            ndr_pull_%s(c, NDR_SCALARS, &%s[_i], d);\n", t->name, acc);
                    fprintf(out_c, "        for (uint32_t _i = 0; _i < _n; _i++)\n");
                    fprintf(out_c, "            ndr_pull_%s(c, NDR_BUFFERS, &%s[_i], d);\n", t->name, acc);
                }
                fprintf(out_c, "    }\n");
            } else if (t->is_string) {
                if (param_has_referent(p)) {
                    fprintf(out_c, "    if (ndr_get_u32(c)) %s = ndr_pull_wstring(c, d);\n", acc);
                } else {
                    fprintf(out_c, "    %s = ndr_pull_wstring(c, d);\n", acc);
                }
            } else if (t->is_sid) {
                fprintf(out_c, "    ndr_pull_sid(c, NDR_SCALARS, &%s);\n", acc);
            } else if ((b != NDR_BUILTIN_NONE || find_enum(t->name)) &&
                       t->nptr >= 1 && t->ptr == NDR_PTR_UNIQUE) {
                /* [in] scalar* with [unique]: referent id then (if non-null) the
                 * value, keeping the cursor aligned for any following params. */
                int bb = (b != NDR_BUILTIN_NONE) ? b : NDR_BUILTIN_UINT32;
                fprintf(out_c, "    if (ndr_get_u32(c)) {\n    ");
                emit_scalar_get(out_c, bb, acc);
                fprintf(out_c, "    }\n");
            } else if (b != NDR_BUILTIN_NONE || find_enum(t->name)) {
                int bb = (b != NDR_BUILTIN_NONE) ? b : NDR_BUILTIN_UINT32;
                emit_scalar_get(out_c, bb, acc);
            } else {
                /* struct, possibly by-ref */
                fprintf(out_c, "    ndr_pull_%s(c, NDR_SCALARS, &%s, d);\n", t->name, acc);
                fprintf(out_c, "    ndr_pull_%s(c, NDR_BUFFERS, &%s, d);\n", t->name, acc);
            }
        }
        fprintf(out_c, "    return c->error ? -1 : 0;\n}\n\n");

        /* ---- push_out ---- */
        fprintf(out_c, "static int\nndr_push_%s_out(struct ndr_writer *w, const void *vp)\n{\n",
                op->name);
        fprintf(out_c, "    const struct %s_out *out = vp;\n", op->name);
        fprintf(out_c, "    (void) out;\n");
        /* Each top-level [out] parameter is marshalled completely (its scalars
         * then its buffers) before the next: top-level params are sequenced,
         * not grouped into one structure.  Grouping all scalars then all
         * buffers desynchronises real clients on ops with multiple pointer
         * outs (verified against samba's NDR for LookupSids/GetUserName). */
        NDR_FOREACH(p, op->params)
        {
            struct ndr_type *t = p->type;
            char             acc[160];
            int              b = classify_builtin(t->name);

            if (!p->out) {
                continue;
            }
            snprintf(acc, sizeof(acc), "out->%s", p->name);

            for (int pass = 0; pass < 2; pass++) {
                const char *flag = pass == 0 ? "NDR_SCALARS" : "NDR_BUFFERS";

                if (t->is_string) {
                    if (pass == 0) {
                        fprintf(out_c, "    ndr_put_ref(w, %s);\n", acc);
                    } else {
                        fprintf(out_c, "    if (%s) %s(w, %s);\n", acc,
                                t->string_nonul ? "ndr_push_wstring_nonul" : "ndr_push_wstring", acc);
                    }
                } else if (t->is_sid) {
                    if (pass == 0) {
                        fprintf(out_c, "    ndr_push_sid(w, NDR_SCALARS, &%s);\n", acc);
                    }
                } else if ((b != NDR_BUILTIN_NONE || find_enum(t->name)) &&
                           t->nptr >= 1 && t->ptr == NDR_PTR_UNIQUE) {
                    /* [out] scalar* with [unique] (e.g. resume_handle): a
                     * referent id (we always have a value, so non-null) then the
                     * value deferred to the buffers pass. */
                    int bb = (b != NDR_BUILTIN_NONE) ? b : NDR_BUILTIN_UINT32;
                    if (pass == 0) {
                        fprintf(out_c, "    ndr_put_ref(w, (const void *) 1);\n");
                    } else {
                        emit_scalar_put(out_c, bb, acc);
                    }
                } else if (b != NDR_BUILTIN_NONE || find_enum(t->name)) {
                    int bb = (b != NDR_BUILTIN_NONE) ? b : NDR_BUILTIN_UINT32;
                    if (pass == 0) {
                        emit_scalar_put(out_c, bb, acc);
                    }
                } else if (t->nptr >= 2) {
                    /* [out] T ** : a unique pointer (the outer *) to the
                     * struct.  Emit its referent id in the scalars pass and the
                     * deferred pointee (scalars+buffers) in the buffers pass.
                     * The _out field stores the inner T * (one level reduced). */
                    if (pass == 0) {
                        fprintf(out_c, "    ndr_put_ref(w, %s);\n", acc);
                    } else {
                        fprintf(out_c, "    if (%s) {\n", acc);
                        fprintf(out_c, "        ndr_push_%s(w, NDR_SCALARS, %s);\n", t->name, acc);
                        fprintf(out_c, "        ndr_push_%s(w, NDR_BUFFERS, %s);\n", t->name, acc);
                        fprintf(out_c, "    }\n");
                    }
                } else {
                    /* [out] T * : top-level ref pointer, no referent id, inline */
                    fprintf(out_c, "    ndr_push_%s(w, %s, &%s);\n", t->name, flag, acc);
                }
            }
        }
        if (op->return_type &&
            classify_builtin(op->return_type->name) != NDR_BUILTIN_VOID) {
            fprintf(out_c, "    ndr_put_u32(w, out->status);\n");
        }
        fprintf(out_c, "    return ndr_writer_length(w);\n}\n\n");
    }
} /* emit_op_funcs */

static void
emit_dispatch_table(void)
{
    struct ndr_op *op;

    if (!g_iface) {
        return;
    }

    fprintf(out_c, "const struct ndr_op_desc %s_op_table[] = {\n", g_iface->name);
    NDR_FOREACH(op, g_iface->ops)
    {
        fprintf(out_c,
                "    { %u, \"%s\", sizeof(struct %s_in), sizeof(struct %s_out), "
                "ndr_pull_%s_in, ndr_push_%s_out },\n",
                op->opnum, op->name, op->name, op->name, op->name, op->name);
    }
    fprintf(out_c, "};\n");
    fprintf(out_c, "const int %s_op_count = sizeof(%s_op_table) / sizeof(%s_op_table[0]);\n\n",
            g_iface->name, g_iface->name, g_iface->name);

    /* interface uuid descriptor */
    fprintf(out_c, "const uint8_t %s_uuid[16] = {", g_iface->name);
    for (int i = 0; i < 16; i++) {
        fprintf(out_c, "%s0x%02x", i ? ", " : "", g_iface->uuid[i]);
    }
    fprintf(out_c, "};\n");
    fprintf(out_c, "const uint16_t %s_ver_major = %u;\n", g_iface->name, g_iface->ver_major);
    fprintf(out_c, "const uint16_t %s_ver_minor = %u;\n\n", g_iface->name, g_iface->ver_minor);

    fprintf(out_h, "extern const struct ndr_op_desc %s_op_table[];\n", g_iface->name);
    fprintf(out_h, "extern const int %s_op_count;\n", g_iface->name);
    fprintf(out_h, "extern const uint8_t %s_uuid[16];\n", g_iface->name);
    fprintf(out_h, "extern const uint16_t %s_ver_major;\n", g_iface->name);
    fprintf(out_h, "extern const uint16_t %s_ver_minor;\n", g_iface->name);
} /* emit_dispatch_table */

/* ------------------------------------------------------------------ */

int
main(
    int    argc,
    char **argv)
{
    if (argc != 4) {
        fprintf(stderr, "usage: ndrzcc <input.idl> <output.c> <output.h>\n");
        return 1;
    }

    yyin = fopen(argv[1], "r");
    if (!yyin) {
        fprintf(stderr, "ndrzcc: cannot open %s\n", argv[1]);
        return 1;
    }

    if (yyparse() != 0) {
        return 1;
    }

    out_c = fopen(argv[2], "w");
    out_h = fopen(argv[3], "w");
    if (!out_c || !out_h) {
        fail("cannot open output files");
    }

    /* ----- header ----- */
    fprintf(out_h, "/* Generated by ndrzcc -- do not edit. */\n");
    fprintf(out_h, "#pragma once\n\n");
    fprintf(out_h, "%s\n", embedded_builtin_h);

    /* ----- source preamble ----- */
    {
        const char *base = strrchr(argv[3], '/');
        base = base ? base + 1 : argv[3];
        fprintf(out_c, "/* Generated by ndrzcc -- do not edit. */\n");
        fprintf(out_c, "#include \"%s\"\n\n", base);
        fprintf(out_c, "%s\n", embedded_builtin_c);
    }

    emit_struct_decls();
    emit_op_io_structs();
    emit_type_funcs();
    emit_op_funcs();
    emit_dispatch_table();

    fclose(out_c);
    fclose(out_h);
    return 0;
} /* main */
